#cloud-config
groups:
  - debian: [root, sys]

users:
  - default
  - name: ${LINUX_USER_DEVOPS_012325}
    gecos: ${LINUX_USER_DEVOPS_012325}
    shell: /bin/bash
    primary_group: ${LINUX_USER_DEVOPS_012325}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    lock_passwd: false
    ssh_authorized_keys: ${LINUX_SSH_KEY_012325}

chpasswd:
  expire: false
  users:
    - name: ${LINUX_USER_DEVOPS_012325}
      password: ${LINUX_PASSWORD_DEVOPS_012325}
      type: text

package_update: true
packages:
  - zsh
  - git

runcmd:
  # - sudo apt-get update
  # This uses Docker's automated script to add their repository and install all dependencies: (It builds based on the most recent stable Official Docker-Built packages, so it's up to date)
  - curl -fsSL get.docker.com | bash
  - sudo usermod -aG docker ${LINUX_USER_DEVOPS_012325}
  - sudo apt-get install docker-compose
  # - apt install -y zsh
  - echo '${LINUX_USER_DEVOPS_012325}:${LINUX_PASSWORD_DEVOPS_012325}' | sudo chpasswd
  # Install Oh My Zsh for the user '${LINUX_USER_DEVOPS_012325}' (change as needed)
  - su - ${LINUX_USER_DEVOPS_012325} -c 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended'
  # Change the default shell to Zsh for the user '${LINUX_USER_DEVOPS_012325}'
  # - chsh -s /bin/zsh ${LINUX_USER_DEVOPS_012325}
  - chsh -s `which zsh` ${LINUX_USER_DEVOPS_012325}
  # Install docker compose
